<a href="https://colab.research.google.com/github/Geethanjali-345/19032024/blob/geethanjali/Copy_of_Wise_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#np reference variable
#seaborn statistical graphs
#label encoding, onehotencoding, getdummies
#eda
#grid search

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Content/survey_lung_cancer.csv')
print("Data imported")

Data imported

In [ ]:
dataset.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [ ]:
dataset.tail()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [ ]:
dataset.describe()

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
count,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000
mean,62.673139,1.563107,1.569579,1.498382,1.501618,1.504854,1.673139,1.556634,1.556634,1.556634,1.579288,1.640777,1.469256,1.556634
std,8.210301,0.496806,0.495938,0.500808,0.500808,0.500787,0.469827,0.497588,0.497588,0.497588,0.494474,0.480551,0.499863,0.497588
min,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,57.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,62.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000
75%,69.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,87.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [ ]:
dataset.describe(include = 'all')

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
count,309,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309
unique,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES
freq,162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270
mean,NaN,62.673139,1.563107,1.569579,1.498382,1.501618,1.504854,1.673139,1.556634,1.556634,1.556634,1.579288,1.640777,1.469256,1.556634,NaN
std,NaN,8.210301,0.496806,0.495938,0.500808,0.500808,0.500787,0.469827,0.497588,0.497588,0.497588,0.494474,0.480551,0.499863,0.497588,NaN
min,NaN,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
25%,NaN,57.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
50%,NaN,62.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,NaN
75%,NaN,69.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN
max,NaN,87.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN

In [ ]:
dataset = pd.get_dummies(dataset)
dataset.head()

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F,GENDER_M,LUNG_CANCER_NO,LUNG_CANCER_YES
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,0,1,0,1
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,0,1,0,1
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,1,0,1,0
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0,1,1,0
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,1,0,1,0

In [ ]:
dataset.info() #dummyvariabletrap

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AGE                    309 non-null    int64
 1   SMOKING                309 non-null    int64
 2   YELLOW_FINGERS         309 non-null    int64
 3   ANXIETY                309 non-null    int64
 4   PEER_PRESSURE          309 non-null    int64
 5   CHRONIC DISEASE        309 non-null    int64
 6   FATIGUE                309 non-null    int64
 7   ALLERGY                309 non-null    int64
 8   WHEEZING               309 non-null    int64
 9   ALCOHOL CONSUMING      309 non-null    int64
 10  COUGHING               309 non-null    int64
 11  SHORTNESS OF BREATH    309 non-null    int64
 12  SWALLOWING DIFFICULTY  309 non-null    int64
 13  CHEST PAIN             309 non-null    int64
 14  GENDER_F               309 non-null    uint8
 15  GENDER_M               309 non-null    uint8
 16  LUNG_CANCER_NO         309 non-null    uint8
 17  LUNG_CANCER_YES        309 non-null    uint8
dtypes: int64(14), uint8(4)
memory usage: 35.1 KB

In [ ]:
dataset = dataset.drop(columns= ['GENDER_M', 'LUNG_CANCER_NO'])
dataset.head()

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F,LUNG_CANCER_YES
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,0,1
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,0,1
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,1,0
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0,0
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,1,0

In [ ]:
dataset = dataset.drop(columns = ['YELLOW_FINGERS', 'PEER_PRESSURE', 'CHRONIC DISEASE', 'ALCOHOL CONSUMING'])
dataset.head()

,AGE,SMOKING,ANXIETY,FATIGUE,ALLERGY,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F,LUNG_CANCER_YES
0,69,1,2,2,1,2,2,2,2,2,0,1
1,74,2,1,2,2,1,1,2,2,2,0,1
2,59,1,1,2,1,2,2,2,1,2,1,0
3,63,2,2,1,1,1,1,1,2,2,0,0
4,63,1,1,1,1,2,2,2,1,1,1,0

In [ ]:
dataset = dataset.drop(columns = ['ALLERGY '])
dataset.head()

,AGE,SMOKING,ANXIETY,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F,LUNG_CANCER_YES
0,69,1,2,2,2,2,2,2,2,0,1
1,74,2,1,2,1,1,2,2,2,0,1
2,59,1,1,2,2,2,2,1,2,1,0
3,63,2,2,1,1,1,1,2,2,0,0
4,63,1,1,1,2,2,2,1,1,1,0

In [ ]:
target = dataset['LUNG_CANCER_YES']
predictor = dataset.drop(columns = ['LUNG_CANCER_YES'])

In [ ]:
print(predictor.head())
print()
print(target.head())

   AGE  SMOKING  ANXIETY  FATIGUE   WHEEZING  COUGHING  SHORTNESS OF BREATH  \
0   69        1        2         2         2         2                    2
1   74        2        1         2         1         1                    2
2   59        1        1         2         2         2                    2
3   63        2        2         1         1         1                    1
4   63        1        1         1         2         2                    2

   SWALLOWING DIFFICULTY  CHEST PAIN  GENDER_F
0                      2           2         0
1                      2           2         0
2                      1           2         1
3                      2           2         0
4                      1           1         1

0    1
1    1
2    0
3    0
4    0
Name: LUNG_CANCER_YES, dtype: uint8

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
predictor = ss.fit_transform(predictor)

In [ ]:
predictor[5:10]

array([[ 1.50382491, -1.13529242, -0.99676897,  0.6968335 ,  0.892475  ,
         0.85220712,  0.74873631, -0.94029056, -1.12047956,  1.04978132],
       [-1.30207786,  0.88083033, -0.99676897,  0.6968335 ,  0.892475  ,
         0.85220712,  0.74873631, -0.94029056,  0.892475  , -0.95257934],
       [-1.42407363,  0.88083033,  1.0032415 ,  0.6968335 , -1.12047956,
        -1.17342366,  0.74873631,  1.06350105, -1.12047956,  1.04978132],
       [ 0.6498545 ,  0.88083033,  1.0032415 ,  0.6968335 , -1.12047956,
        -1.17342366, -1.33558369, -0.94029056, -1.12047956,  1.04978132],
       [-1.18008209,  0.88083033,  1.0032415 , -1.43506304, -1.12047956,
        -1.17342366, -1.33558369,  1.06350105,  0.892475  , -0.95257934]])

In [ ]:
target = target.values
target[5:10]

array([1, 1, 1, 0, 1], dtype=uint8)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(predictor, target, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [ ]:
lr_predicted = lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(lr_predicted, y_test) * 100)

90.32258064516128

#SVM(kernel = 'linear/rbf')
#KNN
#Naive Bayes
#Decision Tree(criterion = 'gini/ entropy')
#Random Forest(criterion = 'gini/ entropy')

#SVM- Linear

In [ ]:
from sklearn import svm
linear_svm = svm.SVC(kernel = 'linear')

In [ ]:
linear_svm.fit(x_train, y_train)

SVC(kernel='linear')

In [ ]:
svm_linearpredict = linear_svm.predict(x_test)

In [ ]:
print(accuracy_score(svm_linearpredict, y_test) * 100)

83.87096774193549

#SVM-rbf

In [ ]:
rbf_svm = svm.SVC(kernel = 'rbf')

In [ ]:
rbf_svm.fit(x_train, y_train)

SVC()

In [ ]:
rbf_prediction = rbf_svm.predict(x_test)

In [ ]:
print(accuracy_score(rbf_prediction, y_test)*100)

85.48387096774194

#KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)

In [ ]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
knnprediction = knn.predict(x_test)

In [ ]:
print(accuracy_score(knnprediction, y_test) * 100)

85.48387096774194

#Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
naive = GaussianNB()

In [ ]:
naive.fit(x_train, y_train)

GaussianNB()

In [ ]:
naivepredictions = naive.predict(x_test)

In [ ]:
print(accuracy_score(naivepredictions, y_test)*100)

88.70967741935483

#Decision Tree - gini

In [ ]:
from sklearn import tree

In [ ]:
treeent = tree.DecisionTreeClassifier(criterion = 'entropy')

In [ ]:
treeent.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
treeentpred = treeent.predict(x_test)

In [ ]:
print(accuracy_score(treeentpred, y_test) * 100)

80.64516129032258

In [ ]:
treegini = tree.DecisionTreeClassifier(criterion = 'gini')

In [ ]:
treegini.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
treeginipred = treegini.predict(x_test)

In [ ]:
print(accuracy_score(treeginipred, y_test) * 100)

80.64516129032258

#Random Forest -gini

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
randforestgini = RandomForestClassifier(criterion = 'gini')

In [ ]:
randforestgini.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
randforestginipred = randforestgini.predict(x_test)

In [ ]:
print(accuracy_score(randforestginipred, y_test) * 100)

88.70967741935483

#Random Forest -entropy

In [ ]:
randentropy = RandomForestClassifier(criterion = 'entropy')

In [ ]:
randentropy.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy')

In [ ]:
randentropypred = randentropy.predict(x_test)

In [ ]:
print(accuracy_score(randentropypred, y_test) * 100)

85.48387096774194

#Parameter tuning(grid search)